name: "workflow principal de cicd"

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout de code
        uses: actions/checkout@v3

      - name: Set up de Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test
