name: workflow principal de cicd

on:
  push:
    branches:
      - main

jobs:
  build-and-test: # Assurez-vous que ce nom est le même partout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build
        run: ./gradlew.bat build
      - name: Test
        run: ./gradlew.bat test
