jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test
